apiVersion: v1
kind: Service
metadata:
  name: hadoop-master2
spec:
  ports:
  - name: ssh
    port: 22
  clusterIP: None
  selector:
    name: hadoop-master2
---
apiVersion: v1
kind: Pod
metadata:
  name: hadoop-master2
  labels:
    app: hadoop-master
    cluster: dta
spec:
  containers:
  - name: hadoop-master2
    image: cu.eshore.cn/library/hadoop:2.6.5
    imagePullPolicy: IfNotPresent
    env:
      - name: TERM
        value: xterm
      - name: USER
        value: hadoop
  nodeSelector:
    hostname: cu2
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-slaver
spec:
  ports:
  - port: 22
  clusterIP: None
  selector:
    name: hadoop-slaver
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hadoop-slaver
spec:
  serviceName: "hadoop"
  replicas: 3
  template:
    metadata:
      labels:
        app: hadoop-slaver
        cluster: dta
    spec:
      containers:
      - name: hadoop-slaver
        image: cu.eshore.cn/library/hadoop:2.6.5
        imagePullPolicy: IfNotPresent
        env:
          - name: TERM
            value: xterm
          - name: USER
            value: hadoop

